name = "EMP"
uuid = "4efe4d37-e9be-5fd9-8821-bff93b12338d"
license = "MIT"
desc = "Extended Mathematical Programming in Julia"
repo = "https://github.com/xhub/EMP.jl.git"
version = "0.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ReSHOP = "97740bd8-9665-555f-bcf8-31e31065c979"

[compat]
julia = "^1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "MathOptInterface", "Test"]
